name: xoxo-AntiCheat
version: '1.0.2'
main: com.xoxoac.XoxoAnticheat
api-version: '1.21'
author: xoxo-AntiCheat Team
description: A highly optimised AntiCheat with Tick Flags, Velocity Levels, auto Ban and exception List

commands:
  virtualsmp:
    description: Main Anticheat Command
    permission: xoxoac.admin
    usage: /<command> [subcommand]

permissions:
  xoxoac.admin:
    description: Full acces to the Plugin
    default: op
